# Generated by Django 6.0.4 on 2026-04-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_alter_manufacturer_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["id"]},
        ),
    ]
