# Generated by Django 6.0.4 on 2026-04-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0004_alter_car_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ["id"],
                "verbose_name": "driver",
                "verbose_name_plural": "drivers",
            },
        ),
    ]
